### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Sean2739** [MestreLion/SimpleInfoHUD#1]
Add reach/combo display and make it a java mod rather than a source file

**Comment by MestreLion** [comment]
Thanks for your feedback!

- What do you mean by "reach/combo" display?

- I believe a (compiled) java mod would be useless now... this was made almost a _decade_ ago, for Minecraft 1.5 / 1.6.2. A **lot** of things have changed since then (I don't think ModLoader exists anymore). I believe creating a new release for current Minecraft will require significant changes in the sources, something I'm unable to do right now.

**Comment by Sean2739** [comment]
No like a reach display would be how far away you hit someone and a combo display would show how many hits you got in a row before being hit, and it would be cool if it was updated to 1.8.9

**Comment by MestreLion** [comment]
> No like a reach display would be how far away you hit someone and a combo display would show how many hits you got in a row before being hit

Thanks, now I understand. Both are very interesting statistics, but I think too specific and out of the scope of a simple and general-use HUD like this. It would be a better fit and a great addition in a combat-oriented HUD, or in a more customizable, powerful one. Have you tried Zyin's HUD?

> it would be cool if it was updated to 1.8.9

1.8.9? That's _very_ different from 1.5.2 this was written for **and** current 1.17.1. Why would you be interested in a rewrite for a now-ancient Minecraft version? I think it would be quite difficult to set up a development environment today for such an old version.

**Comment by Sean2739** [comment]
No I haven't, but that one is 1.8.8

**Comment by Sean2739** [comment]
I would like it to be updated to 1.8.9 so I could use it on hypixel hence why I also requested a reach/combo display

**Comment by MestreLion** [comment]
I see.

Well, I'm sorry, but I have no plans to resume mod development anytime soon, and if I did it would likely be for Minecraft's most recent version, currently 1.17.1

Both the feature you want _and_ your version requirement seem very, very specific to your particular scenario, and not applicable to anyone else, so it will be hard to find a general-use, pre-compiled mod that suits your needs. May I suggest a  a few solutions?

- Find a customizable HUD mod that was released for 1.8.9, and download its `jar`. I'm sure there are many.
- Find one with sources that's close to what you need, adjust it for your needs, then compile it for 1.8.9. You can use my source code as a reference if it helps you in any way.
- Hire someone to do the above for you
